name: promote
version: 0.0.0.0
license: MIT

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

ghc-options: -Weverything
  -Wno-unsafe
  -Wno-missing-import-lists
  -Wno-missing-safe-haskell-mode
  -Wno-prepositive-qualified-module

dependencies:
  - base
  - rio

library:
  source-dirs: src
  dependencies:
    - aeson
    - conduit
    - extra
    - http-conduit
    - optparse-applicative
    - yaml

executables:
  promote:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - promote
