name: Restyled SDK
author: pbrisbin
description: Run commands in restyled:sdk
inputs:
  command:
    description: Full command, passed through sh -c
    required: true
outputs: {}
runs:
  using: docker
  image: docker://restyled/sdk:main
  entrypoint: sh
  args:
    - -c
    - 'REALPWD="$RUNNER_WORKSPACE/$(basename $GITHUB_REPOSITORY)" restyled ${{ inputs.command }}'
