#!/bin/sh
set -eu

tmp=$(mktemp -d)
trap 'rm -rf -- "$tmp"' EXIT

stack build --copy-bins --local-bin-path "$tmp"
cp subcommands/* "$tmp"/

bin=${1:-$HOME/.local/bin}

mkdir -p "$bin"

for subcommand in "$tmp"/*; do
  name=$(basename "$subcommand")
  cp -v "$subcommand" "$bin/restyled-$name"
done

cp -v restyled "$bin"
cp -v restyled-docker "$bin"
