#!/usr/bin/env bash
set -eu

options=(
  --rm
  --env "REALPWD=$PWD"
  --env RESTYLERS_TEST_SHOW
  --volume "$PWD":/code
  --volume /tmp:/tmp
  --volume /var/run/docker.sock:/var/run/docker.sock
)

if [ -t 0 ]; then
  options+=(--interactive --tty)
fi

if [ -n "${AWS_PROFILE:-""}" ]; then
  options+=(--env AWS_PROFILE)
fi

configs=(
  .aws/config
  .aws/credentials
  .docker/config.json
)

for config in "${configs[@]}"; do
  if [ -f "$HOME/$config" ]; then
    options+=(--volume "$HOME/$config:/root/$config:ro")
  fi
done

: "${RESTYLED_SDK_TAG:=main}"

exec docker run "${options[@]}" "restyled/sdk:$RESTYLED_SDK_TAG" "$@"
