#!/usr/bin/env bash
set -eu

options=(
  --rm
  --env "REALPWD=$PWD"
  --volume "$PWD":/code
  --volume /tmp:/tmp
  --volume /var/run/docker.sock:/var/run/docker.sock
)

if [ -t 0 ]; then
  options+=(--interactive --tty)
fi

if [ -n "${AWS_PROFILE:-""}" ]; then
  options+=(--env AWS_PROFILE)
fi

configs=(
  .aws/config
  .aws/credentials
  .docker/config.json
  .netrc
  .netrc.gpg
)

for config in "${configs[@]}"; do
  if [ -f "$HOME/$config" ]; then
    options+=(--volume "$HOME/$config:/root/$config:ro")
  fi
done

: "${GNUPGHOME:=$HOME/.gnupg}"
: "${RESTYLED_SDK_TAG:=:main}"

if [ -d "$GNUPGHOME" ]; then
  options+=(--volume "$GNUPGHOME:/root/.gnupg")
fi

exec docker run "${options[@]}" "restyled/sdk$RESTYLED_SDK_TAG" "$@"
