#!/usr/bin/env bash
set -eu

options=(
  --rm --interactive
  --env "REALPWD=$PWD"
  --volume "$PWD":/code
  --volume /tmp:/tmp
  --volume /var/run/docker.sock:/var/run/docker.sock
)

if [ -t 1 ]; then
  options+=(--tty)
fi

configs=(
  .aws/config
  .aws/credentials
  .docker/config.json
)

for config in "${configs[@]}"; do
  if [ -f "$HOME/$config" ]; then
    options+=(--volume "$HOME/$config:/root/$config:ro")
  fi
done

: "${RESTYLED_SDK_TAG:=''}"
exec docker run "${options[@]}" "restyled/sdk$RESTYLED_SDK_TAG" "$@"
