#!/bin/sh
set -eu

app_env=$1
installation_id=$2
jwt=$(./tools/get-jwt-token "$app_env")

# https://developer.github.com/apps/building-github-apps/authentication-options-for-github-apps/#authenticating-as-an-installation
curl --fail --silent --show-error -X POST \
  -H "Authorization: Bearer $jwt" \
  -H "Accept: application/vnd.github.machine-man-preview+json" \
  "https://api.github.com/app/installations/$installation_id/access_tokens" |
  jq --raw-output '.token // .message'
